title: My house
author: Aimrick_Nya Nya
email: your-email@domain.com
description: > # Welcome to my website that shows the distinct use of my skills
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
